name: EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Action Runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Set Environment Variables
        run: echo "AWS_DEFAULT_REGION=ap-northeast-2" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Add GitHub Actions IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            #!/bin/bash

            API_DIR="/home/ubuntu/Blog_API"
            FLASK_CMD="python3 -u /home/ubuntu/Flask-Chatbot-API/Chatbot.py"
            VENV_ACTIVATE="/home/ubuntu/Flask-Chatbot-API/myvenv/bin/activate"
            LOG_FILE="/home/ubuntu/Flask-Chatbot-API/flask_output.log"

            log_message() {
                echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
            }

            update_api_repo() {
                log_message "Navigating to API directory: $API_DIR"
                if ! cd "$API_DIR"; then
                    log_message "Failed to access the directory: $API_DIR"
                    return 1
                fi

                log_message "Pulling the latest changes from Git"
                if ! git pull; then
                    log_message "Git pull failed in directory: $API_DIR"
                    return 1
                fi

                log_message "Git pull completed successfully"
                return 0
            }

            terminate_flask() {
                log_message "Attempting to find Flask server processes"
                local pids
                pids=$(pgrep -f "$FLASK_CMD")

                if [[ -z "$pids" ]]; then
                    log_message "No Flask server process found running with command: $FLASK_CMD"
                    return 1
                fi

                log_message "Found Flask server processes: $pids"
                for pid in $pids; do
                    log_message "Terminating Flask server process with PID: $pid"
                    if ! sudo kill "$pid"; then
                        log_message "Failed to terminate Flask server process with PID: $pid"
                        return 1
                    fi
                done

                log_message "Flask server processes terminated successfully"
                sleep 5  # Delay to ensure processes are fully terminated and environment stabilizes
                return 0
            }

            activate_venv() {
                log_message "Activating virtual environment: $VENV_ACTIVATE"
                if ! source "$VENV_ACTIVATE"; then
                    log_message "Failed to activate the virtual environment: $VENV_ACTIVATE"
                    return 1
                fi

                log_message "Virtual environment activated successfully"
                return 0
            }

            start_flask() {
                log_message "Starting Flask server with command: $FLASK_CMD"
                nohup $FLASK_CMD > "$LOG_FILE" 2>&1 &
                if [[ $? -ne 0 ]]; then
                    log_message "Failed to start the Flask server with command: $FLASK_CMD"
                    return 1
                fi

                log_message "Flask server started successfully in the background using nohup"
                sleep 5  # Add a delay to ensure the Flask server starts properly
                return 0
            }

            main() {
                log_message "Starting main deployment process"

                if ! update_api_repo; then
                    return 1
                fi

                if ! terminate_flask; then
                    return 1
                fi

                if ! activate_venv; then
                    return 1
                fi

                if ! start_flask; then
                    return 1
                fi

                log_message "Flask server successfully restarted"
            }

            main
          command_timeout: 30m  # Increase the command timeout to 30 minutes
          timeout: 60m  # Increase the overall timeout to 60 minutes

      - name: Remove GitHub Actions IP from Security Group
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
